//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperSetNumber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperSetNumber.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a Number parameter.
        /// </summary>
        public static string ErrorFailedToGetNumberParam {
            get {
                return ResourceManager.GetString("ErrorFailedToGetNumberParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Grid, a Viewport, a Sheet or a Room to set a number..
        /// </summary>
        public static string ErrorNoSelectedElements {
            get {
                return ResourceManager.GetString("ErrorNoSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is read-only.
        /// </summary>
        public static string ErrorParamReadonly {
            get {
                return ResourceManager.GetString("ErrorParamReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select single element..
        /// </summary>
        public static string ErrorSelectOnlyOneElement {
            get {
                return ResourceManager.GetString("ErrorSelectOnlyOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Grids, Viewports, Sheets and Rooms are supported..
        /// </summary>
        public static string ErrorSupportedElements {
            get {
                return ResourceManager.GetString("ErrorSupportedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired grid number:.
        /// </summary>
        public static string LabelGridNumber {
            get {
                return ResourceManager.GetString("LabelGridNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired room number:.
        /// </summary>
        public static string LabelRoomNumber {
            get {
                return ResourceManager.GetString("LabelRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired sheet number:.
        /// </summary>
        public static string LabelSheetNumber {
            get {
                return ResourceManager.GetString("LabelSheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired viewport number:.
        /// </summary>
        public static string LabelViewportNumber {
            get {
                return ResourceManager.GetString("LabelViewportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set number.
        /// </summary>
        public static string TransactionName {
            get {
                return ResourceManager.GetString("TransactionName", resourceCulture);
            }
        }
    }
}
